[project]
name = "artemis-city"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "claude>=0.4.11",
    "claude-code>=0.0.1",
    "npm>=0.1.1",
    "openai>=2.15.0",
    "pytest>=8.4.2",
    "supabase>=2.27.2",
]
